[package]
name = "client"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fluxus"
path = "bin/main.rs"

[lib]
name = "fluxus"
path = "src/lib.rs"

[dependencies.clap]
version = "4.3.0"
features = ["derive"]

[dependencies]
tracing-subscriber.workspace = true
tracing.workspace = true
