[package]
name = "appconf"
version = "0.1.0"
edition = "2021"

[dependencies.thiserror]
workspace = true

[dependencies.appconf-macro]
path = "../appconf-macro"
version = "0.1.0"

[dev-dependencies]
serde = { version = "1.0.152", features = ["derive"] }
toml = "0.7.2"
