[package]
name = "galaxy-shrinker"
version = "0.1.0"
edition = "2021"

[features]
default = ["serde"]
serde = ["dep:serde"]

[dependencies]
zstd-sys = { version = "2.0.7", default-features = false, features = ["thin", "std"] }
negative-impl = "0.1.2"

[dependencies.serde]
workspace = true
optional = true
