[package]
name = "galaxy-shrinker"
version = "0.1.0"
edition = "2021"

[features]
default = ["serde"]
serde = ["dep:serde"]

[dependencies]
negative-impl = "0.1.2"
thiserror = { workspace = true }

[dependencies.zstd-sys]
version = "2.0.7"
default-features = false
features = ["thin", "std"]

[dependencies.serde]
workspace = true
optional = true

[dev-dependencies]
rstest = { version = "0.16.0", default-features = false }
