[package]
name = "galaxy-shrinker"
version = "0.1.0"
edition = "2021"


[dependencies]
negative-impl = "0.1.3"
zstd-sys = { version = "2.0.8", default-features = false, features = [
    "std",
    "thin",
] }
