[package]
name = "galaxy-net-raw"
version = "0.1.0"
edition = "2021"

[features]
default = ["serde"]
serde = ["dep:serde"]

[dependencies]
thiserror = { workspace = true }
serde = { optional = true, workspace = true }

bitflags = { workspace = true }
integral-enum = "2.1.1"
