[workspace]
members = ["packages/*", "bins/*"]

[workspace.dependencies.tracing]
version = "0.1.37"

[workspace.dependencies.tracing-subscriber]
version = "0.3.16"

[workspace.dependencies]
thiserror = "1.0.38"
serde = { version = "1.0.152", features = ["derive"] }
mimalloc = { version = "0.1.34", default-features = false }

bitflags = "1.3.2"
tokio = { version = "1.26.0", features = [
    "rt",
    "rt-multi-thread",
    "io-util",
    "net",
    "sync",
    "macros",
] }
