[workspace]
members = ["crates/*", "server", "client"]

[profile.release]
opt-level = 3
lto = true

[workspace.dependencies.serde]
version = "1.0"
features = ["derive"]

[workspace.dependencies.tokio]
version = "1.28"
features = [
    "net",
    "io-util",
    "rt",
    "rt-multi-thread",
    "parking_lot",
    "sync",
    "macros",
]

[workspace.dependencies]
rstest = "0.17.0"
integral-enum = "3.0.1"
cocoa-purity = "0.1.1"
thiserror = "1.0.40"
cfg-if = "1.0.0"

tracing = "0.1.37"
tracing-subscriber = "0.3.17"

owo-colors = "3.5.0"

envy = "0.4.2"
eyre = "0.6.8"

rustc-hash = "1.1.0"
ahash = "0.8.3"
toml = "0.7.4"
