[workspace]
members = ["client", "server", "crates/*"]

[workspace.dependencies.tokio]
features = ["rt", "rt-multi-thread", "net", "sync", "io-util", "macros"]
version = "1.27"

[workspace.dependencies.serde]
version = "1.0.159"
features = ["derive"]

[workspace.dependencies]
integral-enum = "3.0.0"
thiserror = "1.0.40"
owo-colors = "3.5.0"
envy = "0.4.2"
num_cpus = "1.15.0"
eyre = "0.6.8"

tracing = "0.1.37"
tracing-subscriber = "0.3.16"
