[profile.release]
opt-level = 3
lto = true

[workspace]
members = ["client", "server", "crates/*"]

[workspace.dependencies.galaxy-network]
path = "crates/galaxy-network"
version = "0.1.0"

[workspace.dependencies.tokio]
features = [
    "rt",
    "rt-multi-thread",
    "net",
    "sync",
    "io-util",
    "macros",
    "parking_lot",
    "time",
]
version = "1.27"

[workspace.dependencies.serde]
version = "1.0.159"
features = ["derive"]

[workspace.dependencies]
integral-enum = "3.0.0"
thiserror = "1.0.40"
owo-colors = "3.5.0"
envy = "0.4.2"
num_cpus = "1.15.0"
eyre = "0.6.8"

cocoa-purity = "0.1.1"

tracing = "0.1.37"
tracing-subscriber = "0.3.16"
rustc-hash = "1.1.0"

cfg-if = "1.0.0"
