[package]
name = "neogrok"
version = "0.1.0"
edition = "2021"

[lib]
name = "_stub"
path = "lib/stub.rs"

[workspace]
members = ["packages/*", "bins/*"]

[workspace.dependencies]
thiserror = "1.0.38"
