[workspace]
members = ["packages/*", "bins/*"]

[workspace.dependencies]
thiserror = "1.0.38"
serde = { version = "1.0.152", features = ["derive"] }
mimalloc = { version = "0.1.34", default-features = true }

tokio = { version = "1.26.0", features = [
    "rt",
    "rt-multi-thread",
    "io-util",
    "net",
    "sync",
] }
