[package]
name = "neogrok"
version = "1.0.0"
edition = "2021"
readme = "README.md"
license = "MIT"
repository = "https://github.com/nerodono/neogrok"

[lib]
name = "neogrok"
path = "lib/lib.rs"

[[bin]]
name = "neogrokd"
path = "bin/main.rs"

[profile.release]
lto = true
opt-level = 3

#

[dependencies.mid-net]
path = "packages/mid-net"
version = "1.0.0"

[dependencies.mid-idpool]
path = "packages/mid-idpool"
version = "1.0.0"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

num_cpus = "1.15.0"
toml = "0.7.2"
lazy_static = "1.4.0"
flume = { version = "0.10.14", default-features = false, features = ["async"] }

tracing = "0.1.37"
tracing-subscriber = "0.3.16"
bitflags = "1.3.2"
rustc-hash = "1.1.0"

# Workspace

[workspace]
members = ["packages/*"]

[workspace.dependencies]
integral-enum = "2.1.1"
thiserror = "1.0.38"
serde = { version = "1.0.152", features = ["derive"] }

tokio = { version = "1.25.0", features = [
    "rt",
    "rt-multi-thread",
    "net",
    "sync",
    "macros",
    "io-util",
], default-features = false }
