[package]
name = "mid-compression"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum_dispatch = "0.3.11"
libdeflate-sys = "0.12.0"
zstd-sys = { version = "2.0.7", default-features = false, features = [
    "thin",
    "zdict_builder",
] }
thiserror = { workspace = true }
integral-enum = { workspace = true }
