[package]
name = "server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "neogrokd"
path = "bin/main.rs"

[features]
default = ["galaxy", "http"]
http = []
galaxy = []

[lib]
name = "neo"
path = "src/lib.rs"

[dependencies.idpool]
path = "../crates/idpool"
version = "0.1.0"

[dependencies.galaxy-network]
path = "../crates/galaxy-network"
version = "0.1.0"

[dependencies]
envy.workspace = true
integral-enum.workspace = true
serde.workspace = true
thiserror.workspace = true
owo-colors.workspace = true
eyre.workspace = true

tokio.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true

toml = "0.7.3"
num_cpus.workspace = true
rustc-hash.workspace = true
hyper = { version = "0.14.25", features = ["server", "http1", "http2"] }
paste = "1.0.12"
futures-util = { version = "0.3.28", default-features = false }
http-body-util = "0.1.0-rc.2"
cfg-if = "1.0.0"
