[package]
name = "server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "neogrokd"
path = "bin/main.rs"

[lib]
name = "neo"
path = "src/lib.rs"

[dependencies.idpool]
path = "../crates/idpool"
version = "0.1.0"

[dependencies.galaxy-network]
path = "../crates/galaxy-network"
version = "0.1.0"

[dependencies]
envy.workspace = true
integral-enum.workspace = true
serde.workspace = true
thiserror.workspace = true
owo-colors.workspace = true
eyre.workspace = true

tokio.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true

toml = "0.7.3"
num_cpus.workspace = true
derive_more = { version = "0.99.17", default-features = false, features = [
    "display",
] }
rustc-hash = "1.1.0"
