[package]
name = "galaxy-net"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }

[dependencies.galaxy-net-raw]
version = "0.1.0"
path = "../galaxy-net-raw"

[dependencies.galaxy-shrinker]
version = "0.1.0"
path = "../galaxy-shrinker"

[dependencies.tokio]
workspace = true
features = ["net", "io-util"]
