[package]
name = "server"
version = "0.9.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "fluxus"
path = "src/lib.rs"

[[bin]]
name = "flux-endpoint"
path = "bin/main.rs"

[features]
default = ["tcp", "http", "tcpflux"]
http = []
tcp = []
tcpflux = ["dep:tcp-flux"]

[dependencies.tokio]
workspace = true
features = ["rt", "rt-multi-thread", "net", "sync", "io-util"]

[dependencies.tcp-flux]
workspace = true
optional = true

[dependencies]
flux-common.workspace = true

cfg-if = "1.0.0"
envy = "0.4.2"
num_cpus = "1.16.0"
toml = "0.8.8"

thiserror.workspace = true
tracing-subscriber.workspace = true
integral-enum.workspace = true
tracing.workspace = true
color-eyre.workspace = true
serde.workspace = true
owo-colors.workspace = true
futures-util = { version = "0.3.29", default-features = false, features = [
    "std",
] }
