[package]
name = "mid-net"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["serde"]
serde = ["dep:serde"]

[dependencies.serde]
workspace = true
optional = true

[dependencies.mid-compression]
path = "../mid-compression"
version = "1.0.0"

[dependencies]
tokio = { workspace = true, features = ["net"] }
integral-enum = { workspace = true }

[dev-dependencies]
rstest = { version = "0.16.0", default-features = false }
